name: 'tf deploy to azure'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  
env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ROOT_PATH: '${{ github.workspace }}/src/terraform'
  STORAGE_ACCOUNT_NAME: "mytfstorageaccount1"
  CONTAINER_NAME: "myblobcontainer1"
  FILE_PATH: '${{ github.workspace }}/file_uploads/example.txt'
  AZURE_STORAGE_KEY: ${{secrets.AZURE_STORAGE_KEY}}


jobs:
  terraform_plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ${{env.ROOT_PATH}}
  

  terraform_apply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    needs: [terraform_plan]
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}

    # Generates an execution plan for Terraform
    - name: Terraform Apply
      run: terraform apply --auto-approve
      working-directory: ${{env.ROOT_PATH}}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to storage using CLI
      uses: azure/CLI@v1
      with:
          azcliversion: latest
          inlineScript: |
           az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --account-key ${{secrets.Azure_STORAGE_KEY }} --auth-mode key --overwrite -d ${{env.CONTAINER_NAME}} -s .

  #upload_file:
  #  name: 'upload file to azure storage'
  #  runs-on: ubuntu-latest
  #  needs: [terraform_apply]
  #  environment: production
  # az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT_NAME }} -d ${{env.CONTAINER_NAME}} -s './file_uploads' --pattern "*.txt"

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
  #  defaults:
  #    run:
  #      shell: bash

  #  steps:
    # Checkout the repository to the GitHub Actions runner
  #  - name: Checkout
  #    uses: actions/checkout@v3

  #  - name: Azure Login
  #    uses: azure/login@v1
  #    with:
  #      creds: ${{ secrets.AZURE_CREDENTIALS }}
    
  #  - name: Deploy to storage using CLI
  #    uses: azure/CLI@v1
  #    with:
  #        azcliversion: latest
  #        inlineScript: |
  #          az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT_NAME }} -d ${{env.CONTAINER_NAME}} -s './file_uploads' --pattern "*.txt"

    
    
  #      - name: Azure CLI Upload File
  #    uses: azure/cli@v1
  #   with:
  #      azcliversion: 2.30.0
 #       inlineScript: |
   #       az storage blob upload --account-name $STORAGE_ACCOUNT_NAME --container-name $CONTAINER_NAME --file $FILE_PATH --name example.txt
  #        az storage blob upload-batch --account-name ${{ env.BLOB_STORAGE_ACCOUNT_NAME }} -d '<storagename>' -s './<folder name>' --pattern "*.txt"
